set feedback on

CREATE TABLE SOURCE.CUSTOMER
(
 ID      NUMBER,
 NAME    VARCHAR2(20),
 VERSION NUMBER,
 CONSTRAINT CUSTOMER_PK PRIMARY KEY (ID) USING INDEX COMPUTE STATISTICS TABLESPACE "USERS" ENABLE
) TABLESPACE USERS;

create sequence SOURCE.customer_seq start with 1;

-- #############################################################################################

CREATE TABLE SOURCE.CUSTOMER_ORDER
(
 ID            NUMBER,
 CUSTOMER_ID   NUMBER,
 NAME          VARCHAR2(200),
 VERSION NUMBER,
 CONSTRAINT ORDER_PK PRIMARY KEY (ID) USING INDEX COMPUTE STATISTICS TABLESPACE "USERS" ENABLE,
 CONSTRAINT ORDER_FK FOREIGN KEY (CUSTOMER_ID) REFERENCES SOURCE.CUSTOMER(ID)
) TABLESPACE USERS;

create sequence SOURCE.CUSTOMER_ORDER_seq start with 1;

-- #############################################################################################

CREATE TABLE SOURCE.order_detail
(
 ID         NUMBER,
 ORDER_ID   NUMBER,
 DETAIL     VARCHAR2(200),
 VERSION    NUMBER,
 CONSTRAINT ORDER_DETAIL_PK PRIMARY KEY (ID) USING INDEX COMPUTE STATISTICS TABLESPACE "USERS" ENABLE,
 CONSTRAINT ORDER_DETAIL_FK FOREIGN KEY (ORDER_ID) REFERENCES SOURCE.CUSTOMER_ORDER(ID)
) TABLESPACE USERS;

create sequence SOURCE.order_detail_seq start with 1;

-- #############################################################################################

CREATE TABLE SOURCE.address
(
 ID          NUMBER,
 CUSTOMER_ID NUMBER,
 ADDRESS     VARCHAR2(200),
 VERSION     NUMBER,
 CONSTRAINT ADDRESS_PK PRIMARY KEY (ID) USING INDEX COMPUTE STATISTICS TABLESPACE "USERS" ENABLE,
 CONSTRAINT ADDRESS_FK FOREIGN KEY (CUSTOMER_ID) REFERENCES SOURCE.CUSTOMER(ID)
) TABLESPACE USERS;

create sequence SOURCE.customer_address_seq start with 1;

-- #############################################################################################

CREATE TABLE SOURCE.delivery
(
 ID            NUMBER,
 ORDER_ID      NUMBER,
 ADDRESS_ID    NUMBER,
 NAME          VARCHAR2(200),
 VERSION       NUMBER,
 CONSTRAINT DELIVERY_PK PRIMARY KEY (ID) USING INDEX COMPUTE STATISTICS TABLESPACE "USERS" ENABLE,
 CONSTRAINT DELIVERY_FK1 FOREIGN KEY (ORDER_ID) REFERENCES SOURCE.CUSTOMER_ORDER(ID),
 CONSTRAINT DELIVERY_FK2 FOREIGN KEY (ADDRESS_ID) REFERENCES SOURCE.ADDRESS(ID)
) TABLESPACE USERS;

create sequence SOURCE.delivery_seq start with 1;

